### ISSUE TITLE
Upgrade to PurgeCSS v4

### ISSUE THREAD

**Issue by spacedawwwg** [posthtml/htmlnano#109]
![image](https://media1.tenor.com/images/e81e487a73e35012dab4376a5f6fa98f/tenor.gif?itemid=5636183)

This would technically be a breaking change due to the change in config (e.g 'whitelisting')

**Comment by maltsev** [comment]
Right. I already tried to upgrade it but then the htmlnano API would require a breaking change or a middleware for converting PurgeCSS 2 options to PurgeCSS 3. So I think it's better to just wait until we introduce some other breaking changes in htmlnano so we can release them altogether as the next major version.

**Comment by folknor** [comment]
Just a FYI that PurgeCSS 4 is out, since the issue title mentions "v3".

**Comment by pioug** [comment]
@maltsev What about a major release including svgo 2 and purgecss 4 together? Would it be enough breaking changes? If so, I can make a PR to update svgo.

**Comment by maltsev** [comment]
I don't know. I totally agree that it's good to have dependencies up to date, but releasing a major version just for that, seems like overkill. I doubt, SVGO@2 and PurgeCSS@4 contain significant improvements that would bring value to developers compared to the time they spend upgrading their SVGO and PurgeCSS configs.

**Comment by folknor** [comment]
PurgeCSS@4 uses PostCSS@8, which has much better sourcemap and typescript support.

In any case I don't understand your argument in the context of the world we live in, where semver exists and is ubiquitous. People who want to upgrade will, and people who don't want to upgrade wont.

**Comment by pioug** [comment]
The reason I want to update is because my projects have a mix of PostCSS 7 & 8 right now. I would appreciate to have more common reused dependencies in my `node_modules`.

I still see value for new developers. It's much nicer to deal with updated dependencies. For example, it's not fun to dig into the documentation of older versions, or realize that the features I read about is not available. It's a better developer experience overall.

I don't think the goal is batching a lot of breaking changes either. That would make upgrading even more difficult. 

Technically, a major version is not even necessary since the current one is still 0.x.y (https://semver.org/#doesnt-this-discourage-rapid-development-and-fast-iteration).

Finally, `htmlnano` is great, in a way that you may never need "the" breaking change before a very long time. Pushing back updates may discourage adoption, which in turn may prevent the project to explore new problems (that could be the reason for "the" breaking change).

**Comment by maltsev** [comment]
> Finally, htmlnano is great, in a way that you may never need "the" breaking change before a very long time.

Yes, you're right. That changed my mind :-) I'll do the release over the weekend.

> Technically, a major version is not even necessary since the current one is still 0.x.y

npm won't update 0.x → 0.(x+1) automatically. So in both cases (whether we release 0.3.0 or 1.0.0) a manual upgrade would be required. And I think `htmlnano` is ready to be 1.0.0 :-)

**Comment by pioug** [comment]
@maltsev Thank you so much for your understanding! I gave $5 to PostHTML on Open Collective as a token of appreciation 😄

**Comment by maltsev** [comment]
Done in #138.
