### ISSUE TITLE
"extendDefaultPlugins" utility is deprecated

### ISSUE THREAD

**Issue by frederikhors** [posthtml/htmlnano#150]
I'm getting this message in console:

```
"extendDefaultPlugins" utility is deprecated.
Use "preset-default" plugin with overrides instead.
For example:
{
  name: 'preset-default',
  params: {
    overrides: {
      // customize plugin options
      convertShapeToPath: {
        convertArcs: true
      },
      // disable plugins
      convertPathData: false
    }
  }
}
```

Can we fix this?

**Comment by mischnic** [comment]
This can be fixed by changing

https://github.com/posthtml/htmlnano/blob/3c8ccc8bc0d4af4aa17aac939e1baa10dcc5e0b7/lib/presets/safe.es6#L24

into what the error message suggests and bumping the svgo dependency to `^2.4.0` where this preset was introduced: https://github.com/svg/svgo/releases/tag/v2.4.0

Bumping the dependency would also benefit projects downstream: https://github.com/parcel-bundler/parcel/issues/6744

**Comment by frederikhors** [comment]
> This can be fixed by changing
> 
> https://github.com/posthtml/htmlnano/blob/3c8ccc8bc0d4af4aa17aac939e1baa10dcc5e0b7/lib/presets/safe.es6#L24
> 
> into what the error message suggests and bumping the svgo dependency to `^2.4.0` where this preset was introduced: https://github.com/svg/svgo/releases/tag/v2.4.0
> 
> Bumping the dependency would also benefit projects downstream: [parcel-bundler/parcel#6744](https://github.com/parcel-bundler/parcel/issues/6744)

Can you PR?

**Comment by maltsev** [comment]
I released this patch.
