### ISSUE TITLE
 New dependency name: uglify-es => terser #1 

### ISSUE THREAD

**Issue by fabiosantoscode** [posthtml/htmlnano#52]
There has been development on a new fork of uglify-es, which is now called terser and has its own package!

    "terser": "^3.7.3"

Please upgrade to our new version.

**Comment by maltsev** [comment]
@fabiosantoscode sorry for the late reply. Thanks for letting me know about that new fork! I've added it to the project instead of `uglify-es`.

It took me a while to find information about your fork and why should I use it instead of `uglify-es`. I think some repository owners won't do that and just ignore your proposal. So it might be a good idea to mention some pros of using `terser` instead of `uglify-es` while posting an issue.
