### ISSUE TITLE
Add .htmlnanorc support

### ISSUE THREAD

**Issue by maltsev** [posthtml/htmlnano#63]
For storing configuration.

**Comment by SukkaW** [comment]
Instead of `.htmlnanorc`, I prefer the following formats:

- '.htmlnanorc.cjs',
- '.htmlnanorc.js',
- '.htmlnanorc.yaml',
- '.htmlnanorc.yml',
- '.htmlnanorc.jsonc',
- '.htmlnanorc.json'

I'd like to port the feature from `mochajs`:

https://github.com/mochajs/mocha/blob/1a4646dd2f7b35010c2488edcb2d5f4cfb2f14a8/lib/cli/config.js

**Comment by polarathene** [comment]
You can use [CosmicConfig](https://github.com/davidtheclark/cosmiconfig) as a popular approach for pulling config from a file which supports various formats.

**Comment by maltsev** [comment]
Implemented in 2c03b10d2dfd606c828f66a07ccfb29871afae1c (forgot to add the issue number there).
